var annotated_dup =
[
    [ "GoF_AbstractFactory", "de/d47/namespace_go_f___abstract_factory.html", "de/d47/namespace_go_f___abstract_factory" ],
    [ "GoF_Adapter", "d0/d3d/namespace_go_f___adapter.html", "d0/d3d/namespace_go_f___adapter" ],
    [ "GoF_Bridge", "d7/d87/namespace_go_f___bridge.html", "d7/d87/namespace_go_f___bridge" ],
    [ "GoF_Builder", "d8/df5/namespace_go_f___builder.html", "d8/df5/namespace_go_f___builder" ],
    [ "GoF_ChainOfResponsibility", "da/d8c/namespace_go_f___chain_of_responsibility.html", "da/d8c/namespace_go_f___chain_of_responsibility" ],
    [ "GoF_Command", "d3/dca/namespace_go_f___command.html", "d3/dca/namespace_go_f___command" ],
    [ "GoF_Composite", "d0/de6/namespace_go_f___composite.html", "d0/de6/namespace_go_f___composite" ],
    [ "GoF_Decorator", "d1/d85/namespace_go_f___decorator.html", "d1/d85/namespace_go_f___decorator" ],
    [ "GoF_FactoryMethod", "d2/d1b/namespace_go_f___factory_method.html", "d2/d1b/namespace_go_f___factory_method" ],
    [ "GoF_Flyweight", "d3/d65/namespace_go_f___flyweight.html", "d3/d65/namespace_go_f___flyweight" ],
    [ "GoF_Interpreter", "db/d00/namespace_go_f___interpreter.html", "db/d00/namespace_go_f___interpreter" ],
    [ "GoF_Iterator", "d0/d3c/namespace_go_f___iterator.html", "d0/d3c/namespace_go_f___iterator" ],
    [ "GoF_Mediator", "d5/d7b/namespace_go_f___mediator.html", "d5/d7b/namespace_go_f___mediator" ],
    [ "GoF_Memento", "d9/d9f/namespace_go_f___memento.html", "d9/d9f/namespace_go_f___memento" ],
    [ "GoF_Observer", "de/d9f/namespace_go_f___observer.html", "de/d9f/namespace_go_f___observer" ],
    [ "GoF_Prototype", "db/df0/namespace_go_f___prototype.html", "db/df0/namespace_go_f___prototype" ],
    [ "GoF_Proxy", "d9/dd2/namespace_go_f___proxy.html", "d9/dd2/namespace_go_f___proxy" ],
    [ "GoF_Singleton", "df/df1/namespace_go_f___singleton.html", "df/df1/namespace_go_f___singleton" ],
    [ "GoF_State", "d8/d8b/namespace_go_f___state.html", "d8/d8b/namespace_go_f___state" ],
    [ "GoF_Strategy1", "d1/df3/namespace_go_f___strategy1.html", "d1/df3/namespace_go_f___strategy1" ],
    [ "GoF_Strategy2", "d2/dbe/namespace_go_f___strategy2.html", "d2/dbe/namespace_go_f___strategy2" ],
    [ "GoF_TempateMethod", "d5/dd1/namespace_go_f___tempate_method.html", "d5/dd1/namespace_go_f___tempate_method" ],
    [ "GoF_Visitor", "d4/d8a/namespace_go_f___visitor.html", "d4/d8a/namespace_go_f___visitor" ],
    [ "Sample", "de/df2/namespace_sample.html", "de/df2/namespace_sample" ]
];