var namespaces_dup =
[
    [ "GoF_AbstractFactory", "de/d47/namespace_go_f___abstract_factory.html", null ],
    [ "GoF_Adapter", "d0/d3d/namespace_go_f___adapter.html", null ],
    [ "GoF_Bridge", "d7/d87/namespace_go_f___bridge.html", null ],
    [ "GoF_Builder", "d8/df5/namespace_go_f___builder.html", null ],
    [ "GoF_ChainOfResponsibility", "da/d8c/namespace_go_f___chain_of_responsibility.html", null ],
    [ "GoF_Command", "d3/dca/namespace_go_f___command.html", null ],
    [ "GoF_Composite", "d0/de6/namespace_go_f___composite.html", null ],
    [ "GoF_Decorator", "d1/d85/namespace_go_f___decorator.html", null ],
    [ "GoF_FactoryMethod", "d2/d1b/namespace_go_f___factory_method.html", null ],
    [ "GoF_Flyweight", "d3/d65/namespace_go_f___flyweight.html", null ],
    [ "GoF_Interpreter", "db/d00/namespace_go_f___interpreter.html", null ],
    [ "GoF_Iterator", "d0/d3c/namespace_go_f___iterator.html", null ],
    [ "GoF_Mediator", "d5/d7b/namespace_go_f___mediator.html", null ],
    [ "GoF_Memento", "d9/d9f/namespace_go_f___memento.html", null ],
    [ "GoF_Observer", "de/d9f/namespace_go_f___observer.html", null ],
    [ "GoF_Prototype", "db/df0/namespace_go_f___prototype.html", null ],
    [ "GoF_Proxy", "d9/dd2/namespace_go_f___proxy.html", null ],
    [ "GoF_Singleton", "df/df1/namespace_go_f___singleton.html", null ],
    [ "GoF_State", "d8/d8b/namespace_go_f___state.html", null ],
    [ "GoF_Strategy1", "d1/df3/namespace_go_f___strategy1.html", null ],
    [ "GoF_Strategy2", "d2/dbe/namespace_go_f___strategy2.html", null ],
    [ "GoF_TempateMethod", "d5/dd1/namespace_go_f___tempate_method.html", null ],
    [ "GoF_Visitor", "d4/d8a/namespace_go_f___visitor.html", null ],
    [ "Sample", "de/df2/namespace_sample.html", null ]
];